name: Run Unit Tests

description: Run Unit Tests

inputs:
  CICD_GITHUB_TOKEN:
    required: true
    description: TOKEN

runs:
  using: "composite"
  steps:
  - name: Baixando código do repositório
    uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Adicionando Github Token ao Composer
    env:
      CICD_GITHUB_TOKEN: ${{ inputs.CICD_GITHUB_TOKEN }}
    run: |
      cat <<-EOF > auth.json
      {
        "github-oauth": {
          "github.com": "${CICD_GITHUB_TOKEN}"
        }
      }
      EOF
    shell: bash

  - name: Configurando problem matchers
    run: |
      echo "::add-matcher::.github/matchers/generic.json"
      echo "::add-matcher::.github/matchers/php.json"
      echo "::add-matcher::.github/matchers/phpunit.json"
      echo "::add-matcher::.github/matchers/composer.json"
    shell: bash

  - name: Configurando problem matchers (Third-Party Action)
    uses: mheap/phpunit-matcher-action@b625085ceada5aad0d5b58a87acffae63467d5b1
    with:
      base_path: /var/www/app
